### ISSUE TITLE
[BUG] Commands not Found

### ISSUE THREAD

**Issue by xXQWERTXx** [randy3k/Terminus#152]
When using the `cmd` key to specify shell commands to run on Terminus upon startup, many commands were not found.
Code in default `.sublime_keymap`:
```json
[
    {
        "keys": ["ctrl+alt+shift+t"],
        "command": "terminus_open",
        "args": {
            "cwd": "${file_path:${folder}}",
            "cmd": "node",
        },
    },
]
```
Error returned in Sublime Python logs:
```
FileNotFoundError: The command was not found or was not executable: node.
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 534, in <lambda>
    run_callback('on_pre_close', callback, lambda: callback.on_pre_close(v))
  File "/home/hello/.config/sublime-text-3/Packages/Terminus/terminus/commands.py", line 36, in on_pre_close
    terminal.close()
  File "/home/hello/.config/sublime-text-3/Packages/Terminus/terminus/terminal.py", line 221, in close
    self.process.terminate()
```
Other commands that don't work: `ghci`, `stack` -> they both give the similar `FileNotFoundError`. All commands that aren't working are in my PATH variable.
`python3` does work though, and is the only one that I have found to work.

**Comment by xXQWERTXx** [comment]
(Possibly related to #139)

**Comment by xXQWERTXx** [comment]
Did not see #117. Apologies
