### ISSUE TITLE
Terminus Blank with White Cursor - Windows 10

### ISSUE THREAD

**Issue by apexalexr** [randy3k/Terminus#195]
I have installed and uninstalled both Sublime and the Terminus Package. The error I get in console when I open in panel is:

"Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/core.py", line 639, in run
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/terminal.py", line 219, in activate
  File "C:\Users\apexa\AppData\Roaming\SUBLIM~1\Packages\pywinpty\ST3_WI~2\winpty\ptyprocess.py", line 89, in spawn
    'executable: %s.' % command
FileNotFoundError: The command was not found or was not executable: cmd.exe."

Error for opening in tab is :

"Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/core.py", line 639, in run
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/terminal.py", line 219, in activate
  File "C:\Users\apexa\AppData\Roaming\SUBLIM~1\Packages\pywinpty\ST3_WI~2\winpty\ptyprocess.py", line 89, in spawn
    'executable: %s.' % command
FileNotFoundError: The command was not found or was not executable: cmd.exe."

**Comment by randy3k** [comment]
That’s strange. Terminus cannot find cmd.exe.

**Comment by apexalexr** [comment]
Yeah it's really weird do you have any idea what's causing it. I have 3 drives, however Sublime is installed in C: Also cmd is in C:/Windows/System32/cmd.exe

So it is not like its moved or anything. It isn't just this though its any of the command lines. For instance trying to open powershell will have this.

"Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/core.py", line 639, in run
  File "C:\Users\apexa\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/terminal.py", line 219, in activate
  File "C:\Users\apexa\AppData\Roaming\SUBLIM~1\Packages\pywinpty\ST3_WI~2\winpty\ptyprocess.py", line 89, in spawn
    'executable: %s.' % command
FileNotFoundError: The command was not found or was not executable: powershell.exe."

**Comment by rgolde96** [comment]
I have the same problem

**Comment by rgolde96** [comment]
@apexalexr 
This solution works for me:

1. Navigate to preferences, package settings, Terminus and Open Terminus Command Palette

2. Copy and paste the code below, save and restart ST3

`[
        {
         "caption": "Terminus: Open CMD",
         "command": "terminus_open",
         "args"   : {
             "cmd": ["C:\\windows\\System32\\cmd.exe"],
             "cwd": "${file_path:${folder}}",
             "title": "CMD"
         }
    },
]`

3.  Press CTRL + SHIFT + P to open command palette and open 'Terminus: Open CMD'

**Comment by apexalexr** [comment]
@rgolde96 
Thanks for the suggestion, but when I do that the command doesn't show up in command palette.

**Comment by CHlLDSUPPORT** [comment]
Install "Pywin32" through package manager. It worked for me. :)

**Comment by randy3k** [comment]
I don't think that's the fix. In fact, the `Pywin32` package is broken.

**Comment by submohanty** [comment]
Same error randy, any fixes?

**Comment by randy3k** [comment]
Perhaps Terminus does found cmd.exe. Did you try specifying the full path to cmd.exe?

**Comment by ClintSouthwood** [comment]
You need to exclude **C:\Users\apexa\AppData\Roaming\Sublime Text 3\** from your antivirus. If you have something like MalwareBytes it is blocking Sublime from using WinPTY. Just add it to an exclusion list and you should be good.

**Comment by submohanty** [comment]
So I had 2 python installations on my computer, one from python.org and one downloaded from the microsoft store. I uninstalled the one from the microsoft store and set the PYTHONPATH to the other one and everything works perfectly now
