### ISSUE TITLE
When running terminus it just shows a blank screen

### ISSUE THREAD

**Issue by madhur44** [randy3k/Terminus#228]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\Bhasker\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/core.py", line 824, in run
AttributeError: 'Terminal' object has no attribute 'process'
![sublime](https://user-images.githubusercontent.com/40184545/87519419-33d63f00-c69f-11ea-81b3-e0547f3c3698.png)

**Comment by randy3k** [comment]
For some reasons, cmd.exe cannot be found in the PATH. You might need to either expose it in the system or specify its full path in the Terminus settings.

**Comment by madhur44** [comment]
i get that but how to specify, i can't find any predefined path to edit, in terminus settings. so where to input my cmd path.

**Comment by randy3k** [comment]
in the shell_config.
