### ISSUE TITLE
Migrating build system to Terminus doesn't work

### ISSUE THREAD

**Issue by kevinsjoberg** [randy3k/Terminus#330]
I have the following build system defined in my project.

```json
{
    "build_systems": [
        {
            "name": "Run",
            "selector": "source.odin",
            "cmd": ["odin", "run", "$file"],
            "env": {
                "PATH": "/Users/kevinsjoberg/code/Odin:$PATH"
            },
            "variants": [
                { "name": "Run tests", "cmd": ["odin", "test", "$file"] }
            ],
        },
    ]
}
```

and it works great. I tried to migrate this to Terminus by changing my setup to the following instead.

```json
{
    "build_systems": [
        {
            "name": "Run",
            "selector": "source.odin",
            "cmd": ["odin", "run", "$file"],
            "target": "terminus_exec",
            "cancel": "terminus_cancel_build",
            "env": {
                "PATH": "/Users/kevinsjoberg/code/Odin:$PATH"
            },
            "variants": [
                { "name": "Run tests", "cmd": ["odin", "test", "$file"] }
            ],
        },
    ],
}
```

but it doesn't work. Upon running with this new configuration, I'm greeted with a blank pane. See image below.

<img width="2560" alt="Screenshot 2021-12-20 at 10 15 28" src="https://user-images.githubusercontent.com/503025/146742722-b84ae5ec-07c6-4869-bcd8-b705855e6f08.png">

and the Sublime console spits out the following information:

```console
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/kevinsjoberg/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/render.py", line 45, in run
AttributeError: 'Terminal' object has no attribute 'screen'
Traceback (most recent call last):
  File "/Users/kevinsjoberg/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/commands.py", line 96, in <lambda>
  File "/Users/kevinsjoberg/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/commands.py", line 259, in run_async
  File "/Users/kevinsjoberg/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/terminal.py", line 259, in cancel
AttributeError: 'Terminal' object has no attribute 'process'
```

**Comment by g-regor** [comment]
Same, but on Windows.

The build system with the default config works. Also I can open Terminus in a tab.
But just adding
    
    "target": "terminus_exec",
    "cancel": "terminus_cancel_build",

to the build system config and running the build, throws

    Traceback (most recent call last):
      File "C:\Users\grego\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/commands.py", line 29, in <lambda>
      File "C:\Users\grego\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/commands.py", line 192, in run_async
      File "C:\Users\grego\AppData\Roaming\Sublime Text 3\Installed Packages\Terminus.sublime-package\terminus/terminal.py", line 244, in kill
    AttributeError: 'Terminal' object has no attribute 'process'

**Comment by tomeksowi** [comment]
Same here, can open Terminus tab, build fails. macOS 12.6, Sublime Build 4126.

My config in .sublime-project file (works as expected with "target" and "cancel" commented out):
```json
"build_systems":
[
{
	"name": "Clang single file color",
	"working_dir": "${project_path}",
	"cmd": ["clang", "-fdiagnostics-color=always",  "$file"],
	"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
	// "quiet": true,
	"target": "terminus_exec",
	"cancel": "terminus_cancel_build",
}
]
```

Console output on build:
```
kill
Traceback (most recent call last):
  File "/Users/toms/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/commands.py", line 29, in <lambda>
  File "/Users/toms/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/commands.py", line 192, in run_async
  File "/Users/toms/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/terminal.py", line 244, in kill
AttributeError: 'Terminal' object has no attribute 'process'
```

**Comment by Apis035** [comment]
Anyone got a fix for this?
