### ISSUE TITLE
ST 4170 breaks Terminus

### ISSUE THREAD

**Issue by gobijan** [randy3k/Terminus#411]
Hi after installing the Dev Build 4170 today Terminus broke.
This is what I found in my ST logs:

    reloading python 3.3 plugin Terminus.main
    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
        m = importlib.import_module(modulename)
      File "./python3.3/importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1686, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "/Users/bijan/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/main.py", line 13, in <module>
      File "/Users/bijan/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/events.py", line 142, in post_upgrade
      File "/Users/bijan/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/events.py", line 26, in _tracker
      File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 489, in load_settings
        settings_id = sublime_api.load_settings(base_name)
    RuntimeError: API is not available

**Comment by Afrowave** [comment]
Hey @gobijan,  
  
What I did was uninstall(remove) `terminus` package and reinstall the package.

**Comment by gobijan** [comment]
Wow this worked indeed. Reinstalled and back is my beloved terminal. Not sure how to handle this issue (close or not). Let's let @randy3k  decide.

**Comment by Afrowave** [comment]
A pull request #412 has already been issued that fixes this problem. So we are back to business. 😁

**Comment by randy3k** [comment]
It is fixed by #412.
