### ISSUE TITLE
winpty can't find symlinks, migration to 3.8?

### ISSUE THREAD

**Issue by ghyatzo** [randy3k/Terminus#434]
Hello,

This regards an ongoing issue with the LSP-Julia package: "The embedded Julia REPL doesn't start if Julia was installed via juliaup."
when trying to open a `julia` REPL in a terminus panel and the absolute julia path is not specified a `terminus_open` command is launched for the command `julia`, but the invocation ends with a 
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1482, in run_
    return self.run(edit, **args)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\Terminus.sublime-package\terminus/commands.py", line 542, in run
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\Terminus.sublime-package\terminus/terminal.py", line 232, in start
  File "C:\Users\user\AppData\Roaming\Sublime Text\Lib\python33\winpty\ptyprocess.py", line 89, in spawn
    'executable: %s.' % command
FileNotFoundError: The command was not found or was not executable: julia.
```
although running it both in `PS` and `cmd` works just fine.
There was the same issue with [symlinks](https://github.com/sublimelsp/LSP-julia/issues/24) and `shutil.which` not working properly on python 3.3. And it is also the case here since in `ptyprocess.py` we use `which`.

How much effort would be needed to migrate this package to 3.8?

**Comment by randy3k** [comment]
We have already migrated to python 3.8 runtime. Please upgrade it via Package control.

**Comment by ghyatzo** [comment]
Had to uninstall and reinstall, thought it would move automatically from the old version. Sorry for the useless issue.
