### ISSUE TITLE
no command found after install terminus

### ISSUE THREAD

**Issue by janu17th** [randy3k/Terminus#436]
Sublime Text v4  (Build 4180)
macos 14.5

I install Terminus with package control.  I can see the preference settings but can not see any other commands.  Do I miss some steps to set it up?

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/7a336cf0-e9e0-4a83-b7d6-7068d94596a5">

**Comment by Akashbharatpal** [comment]
The error that I am getting from console is 
```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'ptyprocess' is not currently installed; installing...
Package Control: The dependency 'ptyprocess' has successfully been installed or updated
Package Control: The dependency 'pyte' is not currently installed; installing...
Package Control: The dependency 'pyte' has successfully been installed or updated
Package Control: The dependency 'wcwidth' is not currently installed; installing...
Package Control: The dependency 'wcwidth' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/Terminus/Terminus View.sublime-settings
reloading plugin Terminus.main
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bharatpal/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/main.py", line 18, in <module>
  File "/Users/bharatpal/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/commands.py", line 12, in <module>
  File "/Users/bharatpal/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/recency.py", line 4, in <module>
  File "/Users/bharatpal/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/terminal.py", line 11, in <module>
  File "/Users/bharatpal/Library/Application Support/Sublime Text/Installed Packages/Terminus.sublime-package/terminus/ptty.py", line 7, in <module>
ImportError: cannot import name 'wcwidth' from 'wcwidth' (unknown location)
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by fruffy** [comment]
I am seeing a similar error. Unclear how to fix it.

**Comment by mattwidmann** [comment]
You need to update Package Control to version 4. See https://github.com/wbond/package_control/issues/1612.

**Comment by fruffy** [comment]
What (iirc) ended up working for me is to delete all dependencies on force package control to repull them. Unfortunately I can not provide clear instructions because I ended up deleting non-user packages randomly until the problem resolved itself. I guess I initially ended up in a corrupted state.

**Comment by lawrencedy** [comment]
I encountered this same issue. It is quite ridiculous how we have to upgrade to Package Control v4 manually given it installs v3 when run from Sublime Text, which apparently doesn't work properly with Terminus.

Even after upgrading Package Control, also had tried to delete dependencies ptyprocess, pyte, wcwidth several times just for it to work properly. Not sure what sequence of events I did led to Terminus working, but in any case this issue is quite unacceptable.

**Comment by melvyniandrag** [comment]
Same issue here on both macOS and Windows. Haven't tried the fixes mentioned above.
