### ISSUE TITLE
Exceptions span in console

### ISSUE THREAD

**Issue by CheatEx** [randy3k/Terminus#68]
After opening a terminus panel I get continuous stream of exception in Sublime's console. 

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/home/zan/.config/sublime-text-3/Packages/Terminus/terminus/view.py", line 126, in run
    self.trim_history(edit, terminal)
  File "/home/zan/.config/sublime-text-3/Packages/Terminus/terminus/view.py", line 240, in trim_history
    if lastrow + 1 > n:
TypeError: unorderable types: int() > NoneType()
```

**Comment by CheatEx** [comment]
Also terminal is noticeably lagging and cursor jumps around strangely. Not sure if it makes sense to report these issues while exceptions are falling.

**Comment by randy3k** [comment]
it seems that you have a wrong setting of `scrollback_history_size`. Please double check the setting value and restart Sublime Text.

**Comment by CheatEx** [comment]
@randy3k Copied and pasted it from Default to User settings and exceptions had gone.

Also terminal and SendCode operations much more responsive now. May be it's the real cause of other performance-related issues.
