### ISSUE TITLE
I just can't install Terminus

### ISSUE THREAD

**Issue by drpiou** [randy3k/Terminus#97]
Hi, I just can't install Terminus with Sublime Text 3, I have this error in console during installation process:
```
Package Control: The dependency 'wcwidth' is not currently installed; installing...
Package Control: Error downloading package. URL error [Errno 9] Bad file descriptor downloading https://codeload.github.com/packagecontrol/wcwidth/zip/v0.1.7.
error: Package Control

Unable to download wcwidth. Please view the console for more details.
Package Control: The dependency 'wcwidth' could not be installed or updated
Exception in thread Thread-11323:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 202, in run
    self.result = self.manager.install_package(self.package)
  File "/Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 1531, in install_package
    package_zip.close()
  File "./python3.3/zipfile.py", line 1559, in close
OSError: [Errno 9] Bad file descriptor
```

**Comment by randy3k** [comment]
Please try agian later, or report to Package Control. It is an issue related to Package Control.

**Comment by drpiou** [comment]
Okay, thanks!
